# Generated by Django 4.1 on 2022-10-13 19:47

from django.conf import settings
import django.contrib.auth.base_user
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMain', '0002_tarefas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
