# Generated by Django 4.1 on 2022-10-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0003_alter_tarefas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='usuario',
        ),
    ]
