# Generated by Django 4.1.1 on 2022-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0005_tarefas_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='link',
            field=models.URLField(),
        ),
    ]
