# Generated by Django 4.1.1 on 2022-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0007_alter_tarefas_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
