# Generated by Django 4.1.1 on 2022-12-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0009_alter_tarefas_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
