# Generated by Django 4.1.1 on 2022-12-16 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appMain', '0013_remove_tarefas_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
